### ISSUE TITLE
Compiling on RHEL8 fails

### ISSUE THREAD

**Issue by christophfroehlich** [PickNikRobotics/RSL#114]
Hi, it's me again trying to get a CI pipeline for humble@RHEL working.

But there is some issue with Eigen:
```
Starting >>> rsl     
--- stderr: rsl                         
CMake Error at CMakeLists.txt:25 (target_link_libraries):
  Target "rsl" links to:

    Eigen3::Eigen

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

I was able to fix this by just not link the library but add the include folders: https://github.com/christophfroehlich/RSL/commit/8d2bacef568c2ec45705dee04ed8793d3414ca20

I don't have much experience with Eigen, but as it is a header-only library, why should one link against it? 

With the released version of Eigen on rhel8 there are a lot of build warnings -> I also had to change the compiler flags. 

A newer release of Eigen (3.4 for example) hasn't fixed any of those issues.

**Comment by ChrisThrasher** [comment]
Linking against CMake targets is the canonical way to express dependencies. One of the benefits is that it ensures warnings aren’t applied to Eigen headers as you’re seeing. We would not consider what you proposed.

**Comment by christophfroehlich** [comment]
I see. But apparently, it introduces other issues..
Any suggestions how to fix the original "target not found" error then? 

Btw other packages don't do it in the linking-way, e.g., the [admittance_controller](https://github.com/ros-controls/ros2_controllers/blob/master/admittance_controller/CMakeLists.txt#L53) with origins from PickNik, too. :man_shrugging: Do you have any resources for me for best practices on that topic?

**Comment by ChrisThrasher** [comment]
https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html

We’re doing exactly what Eigen recommends. Perhaps your OS is too old for your Eigen installation to include this CMake target.

**Comment by christophfroehlich** [comment]
Thanks for the link, maybe I have to set CMAKE_PREFIX_PATH on this platform.

**Comment by ChrisThrasher** [comment]
`NO_MODULE` ensures that Eigen3Config.cmake gets used in lieu of FindEigen3.cmake assuming such a file exists. That’s fine by me. Whatever FindEigen3.cmake module is being found on your machine obviously isn’t sufficient since it does not define the `IMPORTED` CMake target that Eigen3Config.cmake defines. I think I’m fine with a PR that makes such a change especially if that’s what the docs already recommend.

If I had to guess FindEigen3.cmake is some legacy relic from a time before the library provided a config module. 1st party config modules are always preferable to find modules when available.

**Comment by christophfroehlich** [comment]
Thanks @ChrisThrasher for your help!

**Comment by christophfroehlich** [comment]
Now are other jobs failing using generate_parameter_library with the same error (both are built from source)
https://github.com/ros-controls/control_toolbox/actions/runs/8037264479/job/21951911473#step:7:19

Must this `NO_MODULE`|`CONFIG` now also be passed to to `find_package(rsl)`? And as a consequence also to `find_package(generate_parameter_library)`?
https://github.com/PickNikRobotics/generate_parameter_library/blob/main/generate_parameter_library/generate_parameter_library-extras.cmake#L32

**Comment by ChrisThrasher** [comment]
> Now are other jobs failing using generate_parameter_library with the same error (both are built from source) https://github.com/ros-controls/control_toolbox/actions/runs/8037264479/job/21951911473#step:7:19
> 
> Must this `NO_MODULE`|`CONFIG` now also be passed to to `find_package(rsl)`? And as a consequence also to `find_package(generate_parameter_library)`? https://github.com/PickNikRobotics/generate_parameter_library/blob/main/generate_parameter_library/generate_parameter_library-extras.cmake#L32

https://github.com/PickNikRobotics/RSL/tree/eigen

Please test this out.
